### ISSUE TITLE
[Feat] QR 개인정보 입력 + 자잘한 마크업

### ISSUE THREAD

**Issue by kauthenticity** [healthier-devs/healthier-frontend#120]
## ✏️ 기능 개요
- QR 정보 수집 페이지 
- 자잘한 마크업

## ✅ TODO
- [x] QR 정보 수집 페이지
- [x] NUMBER_1 버튼 UI 수정
- [x] 치과 로직 마지막 text area 
- [x] 결과 상세 페이지 로딩창
- [x] 진단 이미지 url에 severity 추가
- [x] 치과 진단 후 로딩 페이지
- [x] QR 증상 선택 페이지
- [x] QR 환자 문진차트 생성
- [x] QR 문진 후 대기 화면
- [x] soaps시 query string의 hospitalId 사용
- [x] 이미지 url 연결
