### ISSUE TITLE
[Feat] 회원가입 예외 처리 화면 구현

### ISSUE THREAD

**Issue by kauthenticity** [healthier-devs/healthier-frontend#145]
## ✏️ 기능 개요
- 회원 가입 시 발생하는 예외 상황에 대한 화면을 구현합니다.

## ✅ TODO
- [ ] 가입이 제한된 사용자
- [ ] 탈퇴 후 재가입 기간이 안 지난 사용자
- [ ] 이전에 같은 메일로 가입한 사용자
