### ISSUE TITLE
[Feat] 건강 챌린지 상세 페이지 구현

### ISSUE THREAD

**Issue by moong23** [healthier-devs/healthier-frontend#147]
## ✏️ 기능 개요
- 건강 챌린지 상세 페이지
## ✅ TODO
- [x] 건강 챌린지 상세 페이지 마크업 마무리
- [x] 건강 챌린지 상세 페이지 api 연동
- [ ] 추가 작업 필요 : 인증가이드 디자인 완료되면 수정필요
