### ISSUE TITLE
[Feat] 환경설정 화면 구현

### ISSUE THREAD

**Issue by kauthenticity** [healthier-devs/healthier-frontend#168]
## ✅ TODO
- [x] 환경설정 화면 마크업
- [ ] 앱 푸시 알림 동의 api 연결
- [ ] 마케팅 알림 동의 api 연결
- [x] 로그아웃 api 연결
- [ ] 회원탈퇴 api 연결
