### ISSUE TITLE
[Feat] 메인 화면 개발

### ISSUE THREAD

**Issue by kauthenticity** [healthier-devs/healthier-frontend#192]
## ✏️ 기능 개요
- 미완성된 메인 화면 개발

## ✅ TODO
- [x] 광고 API 연결
- [ ] 연령별 다빈도 질환
- [ ] 로그인 여부에 따른 챌린지 처리
- [ ] 로그인 여부에 따른 건강 기록장 처리
