### ISSUE TITLE
[Fix] 마이페이지 버그 수정 

### ISSUE THREAD

**Issue by kauthenticity** [healthier-devs/healthier-frontend#216]
## ✏️ 기능 개요
마이페이지 버그 수정

## ✅ TODO
- [ ] 프로필 사진 제거
- [ ] 프로필 수정 -> 이메일 반영, 전화번호 제거
- [ ] 건강 기록장 내림차순 정렬
