### ISSUE TITLE
[Fix] 챌린지 리워드 QA

### ISSUE THREAD

**Issue by kauthenticity** [healthier-devs/healthier-frontend#218]
## 🐞 버그 개요
챌린지 리워드와 관련된 QA

## ✅ TODO
- [x] 마이페이지 선물함 바로가기 url 연결
- [ ] 이미지 엑박 수정
- [x] 마크업 수정
- [x] 비로그인 사용자 챌린지 참여 대응
