### ISSUE TITLE
[Feat] 급성복통 로직 구현

### ISSUE THREAD

**Issue by jhj2713** [healthier-devs/healthier-frontend#67]
## ✏️ 기능 개요
- 급성 복통 로직 구현

## ✅ TODO
- [x] 급성 복통 로직 분석
- [x] 급성 복통 로직 구현
- [x] 급성 복통 API 연동
