### ISSUE TITLE
[Feat] 배변이상 로직 구현

### ISSUE THREAD

**Issue by jhj2713** [healthier-devs/healthier-frontend#68]
## ✏️ 기능 개요
- 배변이상 로직

## ✅ TODO
- [x] 배변이상 로직 분석
- [x] 배변이상 로직 구현
- [x] 배변이상 API 연동
