### ISSUE TITLE
[Feat] 허리 통증 로직 구현

### ISSUE THREAD

**Issue by kauthenticity** [healthier-devs/healthier-frontend#69]
## ✏️ 기능 개요
- 허리 통증 로직을 구현한다.

## ✅ TODO
- [x] 허리 통증 로직 분석
- [x] 허리 통증 로직 구현
- [x] 허리 통증 API 연동
