### ISSUE TITLE
[Feat] 병원 예약 UI 구현

### ISSUE THREAD

**Issue by jhj2713** [healthier-devs/healthier-frontend#91]
## ✏️ 기능 개요
병원 예약 UI

## ✅ TODO
- [x] 지도 연동 구현
- [ ] Bottom Sheet 구현
- [ ] 검색 구현
- [ ] 병원 정보 api 연동
